//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotoTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fotoTb()
        {
            this.hastaTb = new HashSet<hastaTb>();
        }
    
        public int fotografId { get; set; }
        public string fotoPath { get; set; }
        public Nullable<int> hastaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hastaTb> hastaTb { get; set; }
    }
}
