//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaTakip.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hastatakipdbEntities : DbContext
    {
        public hastatakipdbEntities()
            : base("name=hastatakipdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doktorTb> doktorTb { get; set; }
        public virtual DbSet<fotoTb> fotoTb { get; set; }
        public virtual DbSet<hastaTb> hastaTb { get; set; }
        public virtual DbSet<sikayetTb> sikayetTb { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
