//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sikayetTb
    {
        public int sikayetId { get; set; }
        public Nullable<int> doktorId { get; set; }
        public Nullable<int> hastaId { get; set; }
        public string sikayet { get; set; }
        public string teshis { get; set; }
        public Nullable<System.DateTime> girisTarihi { get; set; }
        public Nullable<System.DateTime> cikisTarihi { get; set; }
    
        public virtual doktorTb doktorTb { get; set; }
        public virtual hastaTb hastaTb { get; set; }
    }
}
